# Generated by Django 4.2.7 on 2023-11-05 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='наименование')),
                ('description', models.TextField(max_length=0, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='наименование')),
                ('description', models.TextField(max_length=0, verbose_name='описание')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='mainapp/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='цена')),
                ('data_life', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('data_chadge', models.DateField(blank=True, null=True, verbose_name='дата_изменения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
    ]
